# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('image', models.URLField(max_length=2000)),
                ('description', models.CharField(max_length=1000)),
                ('branding', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('currencies', models.CharField(max_length=2000)),
                ('setup_fee', models.IntegerField()),
                ('transaction_fees', models.CharField(max_length=1000)),
                ('how_to_url', models.URLField(max_length=2000)),
            ],
        ),
    ]
