# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_payment', '0002_auto_20160306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='rating',
            field=models.FloatField(),
        ),
    ]
